# Generated by Django 5.2 on 2025-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='data_termino',
            field=models.DateTimeField(),
        ),
    ]
