# Generated by Django 5.2 on 2025-05-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reserva_ambiente_data_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_ambiente',
            old_name='data_inicio',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='reserva_ambiente',
            name='data_termino',
        ),
    ]
