# Generated by Django 5.2 on 2025-05-06 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reserva_ambiente_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='sala_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='app.sala'),
        ),
    ]
