# Generated by Django 5.2 on 2025-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_disciplinar_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='data_termino',
            field=models.DateField(),
        ),
    ]
