# Generated by Django 5.2 on 2025-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reserva_ambiente_sala_reservada'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinar',
            name='carga_horaria',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
